# Generated by Django 5.0.3 on 2026-01-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MLE', 'MLE Logistic Regression'), ('Bayes_HMC', 'Bayesian HMC Logistic Regression'), ('Bayes_Gibbs', 'Bayesian Gibbs Logistic Regression')], max_length=20)),
                ('version', models.CharField(default='v1', max_length=50)),
                ('pr_auc', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('model_file', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
